
GET http://localhost:4000/y  HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjQ3LCJ1c2VyTmFtZSI6ImpvaG4iLCJpYXQiOjE2NjY2MTUyODB9.D22vDhbeqIvRaJ19M0NEn4im4o812hVt3zMotYpxy90

###

POST http://localhost:4000/login  HTTP/1.1
content-type: application/json

{
    "username": "john",
    "password": "abc"
}

###

POST http://localhost:4000/createuser  HTTP/1.1
content-type: application/json

{
    "username": "john3",
    "password": "abc"
}

###

POST http://localhost:4000/entry  HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjQ3LCJ1c2VyTmFtZSI6ImpvaG4iLCJpYXQiOjE2NjY2MTUyODB9.D22vDhbeqIvRaJ19M0NEn4im4o812hVt3zMotYpxy90

{
    "entryTitle": "posting again 2",
    "entryText": "post without url",
    "entryUrl": ""
}

###

GET http://localhost:4000/entries HTTP/1.1
Authorization: Bearer 12345


